### ISSUE TITLE
Can't build on Rust Stable 1.36.0

### ISSUE THREAD

**Issue by jacksapper** [Skytrias/everpuzzle#44]
```Compiling amethyst_assets v0.6.0 (https://github.com/amethyst/amethyst?rev=36501cf580d1f7a41a787e470e431aef613d8875#36501cf5)
error[E0283]: type annotations required: cannot resolve `std::string::String: std::convert::AsRef<_>`
   --> /Users/jasonhatton/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/36501cf/amethyst_assets/src/prefab/mod.rs:372:22
    |
372 |                 name.as_ref(),
    |                      ^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0283`.
error: Could not compile `amethyst_assets`.
```

**Comment by Skytrias** [comment]
now running on stable 1.4 with the entire rebuilding of the game
