### ISSUE TITLE
Can't build on 1.30.0 (stable) or 1.31.0 (nightly)

### ISSUE THREAD

**Issue by lcowell** [Skytrias/everpuzzle#22]
Hi there, I'm unable to build this project on stable or night getting the same error. A little googling suggested that bindgen might need to be updated.

```
  Compiling amethyst_renderer v0.9.0
error: failed to run custom build command for `coreaudio-sys v0.2.2`
process didn't exit successfully: `$HOME/src/everpuzzle/target/debug/build/coreaudio-sys-22ecccdac708f029/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=framework=AudioUnit
cargo:rustc-link-lib=framework=CoreAudio

--- stderr
/usr/local/include/Block.h:16:3: error: Never include this file directly. Use <lzma.h> instead.
/usr/local/include/Block.h:93:2: error: unknown type name 'lzma_check'
/usr/local/include/Block.h:148:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:172:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:200:2: error: unknown type name 'lzma_filter'
/usr/local/include/Block.h:217:20: error: use of undeclared identifier 'LZMA_CHECK_SIZE_MAX'
/usr/local/include/Block.h:231:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:232:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:233:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:234:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:235:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:236:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:237:2: error: unknown type name 'lzma_reserved_enum'
/usr/local/include/Block.h:238:2: error: unknown type name 'lzma_reserved_enum'
/usr/local/include/Block.h:239:2: error: unknown type name 'lzma_reserved_enum'
/usr/local/include/Block.h:240:2: error: unknown type name 'lzma_reserved_enum'
/usr/local/include/Block.h:261:2: error: unknown type name 'lzma_bool'
/usr/local/include/Block.h:263:2: error: unknown type name 'lzma_bool'
/usr/local/include/Block.h:264:2: error: unknown type name 'lzma_bool'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
/usr/local/include/Block.h:16:3: error: Never include this file directly. Use <lzma.h> instead., err: true
/usr/local/include/Block.h:93:2: error: unknown type name 'lzma_check', err: true
/usr/local/include/Block.h:148:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:172:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:200:2: error: unknown type name 'lzma_filter', err: true
/usr/local/include/Block.h:217:20: error: use of undeclared identifier 'LZMA_CHECK_SIZE_MAX', err: true
/usr/local/include/Block.h:231:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:232:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:233:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:234:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:235:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:236:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:237:2: error: unknown type name 'lzma_reserved_enum', err: true
/usr/local/include/Block.h:238:2: error: unknown type name 'lzma_reserved_enum', err: true
/usr/local/include/Block.h:239:2: error: unknown type name 'lzma_reserved_enum', err: true
/usr/local/include/Block.h:240:2: error: unknown type name 'lzma_reserved_enum', err: true
/usr/local/include/Block.h:261:2: error: unknown type name 'lzma_bool', err: true
/usr/local/include/Block.h:263:2: error: unknown type name 'lzma_bool', err: true
/usr/local/include/Block.h:264:2: error: unknown type name 'lzma_bool', err: true
fatal error: too many errors emitted, stopping now [-ferror-limit=], err: true
thread 'main' panicked at 'unable to generate bindings: ()', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Skytrias** [comment]
hey @lcowell cool to see some new people interested in this project. could you tell me your specs and OS? Its really important on Linux for example that you download some libraries for amethyst https://www.amethyst.rs/book/master/getting-started.html#required-dependencies

im running windows 10 and its been working pretty good, ill update my rust version and see if i can reproduce anything

**Comment by Skytrias** [comment]
also run rustup update and see if it works by rerunning cargo run. im pretty sure amethyst is using up to date syntax. if that doesnt work, have you tried running amethyst's examples? https://github.com/amethyst/amethyst/tree/master/examples

**Comment by lcowell** [comment]
Thanks for getting back to me. I'm running OSX 10.14.1 on a MBP w/ 32GB RAM.

This same issue is present when I try to build the examples, so I'll focus my attention there. If I come up with something useful to add to your readme, I'll open a PR. Thanks again!

**Comment by lcowell** [comment]
Looks like I had a package install on my system that offered a conflicting `Block.h`. If I remove that file, the project compiles without issue. Thank you.

**Comment by Skytrias** [comment]
@lcowell Alright thanks for letting me know!
